name: Init_3.2.2
description: Theme used in PureBuilder Simply 3.2.2's pbsimply-init.
initial_control:
  build_cpr:
    - [css]
    - [javascript]
    - [js]
    - [img]
variables:
  lang: ja
  baseurl: "/"
  favicon: "img/favicon.ico"
  title-prefix: "Copyright 2025 kinoko1943, Powered by PureBuilder Simply"
  include-before:
    - before.html
  include-after:
    - after.html
  toc: true
  idprefix: ""
  menu-Toggle-label: "☰"
  menu-Toggle-aria-controls: "before"
  menu-Toggle-aria-expanded: "false"
  menu-Toggle-title: "Menu Toggle"
  scrim-id: "scrim"
  scrim-hidden: "hidden"
  scrim-style: ""
  scrim-aria-hidden: "true"
  scrim-tabindex: "-1"
  scrim-role: "button"
  scrim-aria-label: "Close Menu"
  scrim-aria-controls: "before"
  scrim-aria-expanded: "false"
  scrim-title: "Close Menu"
  scrim-onclick: "toggleMenu();"
header-includes:
  - '<script src="javascrript/before-Toggle.js" defer></script>'  